export type HelperPlatform = "Windows" | "macOS" | "Linux";

export function localHelperSpec(platform: HelperPlatform, origin: string, providerHost: string) {
  return `Build a complete, runnable local IPTV playback helper for ${platform}.

I will paste these instructions into an AI coding assistant. Produce all source files, dependency manifests, configuration templates, installation commands, start/stop instructions, troubleshooting and tests. Do not assume access to the original repository. Implement the exact browser protocol below; do not require changes to the existing website. Prefer JavaScript ES modules on a supported Node.js LTS release with native node:http, node:crypto and node:child_process, plus dotenv. FFmpeg is a separate installed executable.

PURPOSE AND NETWORK MODEL
The website runs at ${origin}. Its JavaScript executes in my browser on this same computer. The helper listens ONLY on http://127.0.0.1:19876 (IPv4 loopback, never 0.0.0.0 or the LAN address). Browser -> local helper -> IPTV provider; the helper returns progressive MPEG-TS video to the browser's mpegts.js player. No video passes through Vercel. No router forwarding, public server, tunnel or hosted gateway is needed. Chrome/Edge may require local-network permission; CORS headers do not replace that permission. Do not disable browser security. Desktop Chrome/Edge are the initial target even on macOS; do not promise universal Safari/mobile support.

CONFIGURATION (LOCAL FILES ONLY)
Provide .env.example with:
LOCAL_PLAYER_ORIGINS=${origin}
LOCAL_PLAYER_HOSTS=${providerHost || "REPLACE_WITH_TRUSTED_PROVIDER_HOST"}
# Optional absolute path; default resolves ffmpeg from PATH:
# LOCAL_PLAYER_FFMPEG=/replace/with/platform/ffmpeg/path

Origins are exact scheme + hostname + optional port, comma-separated, with no path or wildcard. Provider entries are exact URL.host values (hostname plus non-default port), comma-separated. Never allow all hosts by default. These values identify the current website and provider host only; no stream URL, account password, token or movie title is included in this specification. Ask the user to confirm additional trusted providers if necessary. No IPTV credentials need to be configured separately: the browser supplies a complete authenticated source URL when creating a session. Keep that URL in memory only, never log or persist it. Treat configuration strings as data, never shell code. Optional compatibility with existing XC_SERVER_1..XC_SERVER_10 URLs may extract their URL.host into the allowlist. Standalone operation must work using LOCAL_PLAYER_HOSTS alone. Load ignored .env.local relative to the helper directory, not an arbitrary working directory; process environment takes precedence. Keep port 19876 because the existing player hardcodes it.

EXACT HTTP API, VERSION 1
For all requests require Host: 127.0.0.1:19876. Playback APIs, health and preflight requests require an Origin in the exact configured allowlist; otherwise 403. Exceptions for the read-only HTML, static script and same-origin status refresh are narrowly defined below. If an Origin is supplied on an exception route it must still be approved. Sessions also belong to their creating Origin. For accepted API origins set Access-Control-Allow-Origin to that origin, Vary: Origin and Cache-Control:no-store, including errors. Never use wildcard CORS.

OPTIONS: respond 204 with Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS; Access-Control-Allow-Headers: content-type; Access-Control-Allow-Private-Network: true. This supports older preflight behavior; modern browsers can still ask for local-network permission.

GET /health: 200 application/json whether ready or needing attention; retain version:1 for playback protocol compatibility and add healthSchema:2. The frontend treats old {"version":1} responses as detected but readiness unknown, never green. Implement this exact expanded shape (example values):
{"version":1,"healthSchema":2,"helperVersion":"1.1.0","ready":true,"checkedAt":"2026-01-01T00:00:00.000Z","address":"127.0.0.1","port":19876,"statusUrl":"http://127.0.0.1:19876/","problems":[],"ffmpeg":{"available":true,"version":"8.0","aac":true,"h264":true,"checkedAt":1767225600000,"error":null},"modes":{"remux":true,"compatible":true},"system":{"platform":"win32","release":"OS release","arch":"x64","node":"v24.0.0","logicalCpus":8,"totalMemoryMB":16384,"freeMemoryMB":8192,"helperUptimeSeconds":60},"configuration":{"allowedOrigins":["<configured website origin>"],"providerHosts":["<configured provider host>"]},"sessions":{"active":0,"allocated":0,"limit":2}}
Populate actual values, never pretend the example versions describe the user's machine. Probe ffmpeg -version and ffmpeg -hide_banner -encoders asynchronously, with five-second process timeouts, bounded output and no shell. Parse AAC and libx264 encoder availability. Cache/coalesce binary checks for 30 seconds to avoid spawning processes for every health poll. Always recompute dynamic memory/session/uptime values. ready is true only when FFmpeg runs, both encoders exist, at least one provider is configured, and fewer than two session slots are allocated. modes.remux needs FFmpeg+AAC; modes.compatible needs FFmpeg+AAC+libx264. Populate safe actionable problems when not ready. Do not return executable/home paths, raw command output or secrets in errors. Ready does NOT assert provider/account access, source validity, or browser codec support.

GET /: serve an escaped, responsive read-only HTML dashboard with no credential entry. Direct navigation can omit Origin. Show readiness, loopback IP+port, FFmpeg/encoders, OS/architecture/Node, CPU count, memory, uptime, sessions, configuration and telemetry below. Explain operation, NAT, bandwidth, modes, limitations and troubleshooting. Use Cache-Control:no-store, X-Frame-Options:DENY, Referrer-Policy:no-referrer, X-Content-Type-Options:nosniff and CSP default-src 'none'; script-src 'self'; connect-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'. Serve a fixed local script at GET /status.js (JavaScript MIME, strict Host, no Origin required for a same-origin script load). No inline/eval scripts or external analytics. Escape server HTML; use textContent/DOM creation for live data, never telemetry as innerHTML. Update elements every two seconds without a full-page refresh; offer 2/5/10-second intervals, Refresh now, Pause/Resume and a Reload page fallback without JavaScript. Pause automatic polling while hidden, coalesce calls, use eight-second timeouts and mark stale data on errors. Include a 60-sample aggregate output-throughput chart with units/scale and detailed stream cards. Support light/dark themes and narrow screens.

GET /status: return the same expanded snapshot as /health. Require strict Host, plus either an approved website Origin OR missing Origin with Sec-Fetch-Site: same-origin for the local page's fetch. Reject missing Origin without same-origin Fetch Metadata, cross-site fetches and supplied unapproved origins. Return exact CORS headers only for approved origins. Do not extend this exception to /health or /sessions. Static scripts/HTML contain no session tokens or credentials.

LIVE TELEMETRY EXTENSION (helperVersion 1.2.0; keep version:1 and healthSchema:2)
Add telemetrySchema:1; system.helperMemoryMB (Node RSS only); transfer:{bytesSent:<output bytes since startup>,streamsStarted:<process starts>,providerDownloadMbps:null,measurement:<explanation>}; streams:[...]. Each session has a sanitized entry, never its secret ID: {number:<display index>,mode,source:<scheme://host/… with path/query hidden>,extension:<file extension or null>,state:<waiting|starting|streaming|no recent output>,outputContainer:"mpegts",bytesSent,currentMbps,averageMbps,peakMbps,elapsedSeconds,lastOutputSecondsAgo,progressAgeSeconds,frames,processingFps,mediaSeconds,speed,outputKbps,droppedFrames,duplicatedFrames,input:{container,videoCodec,audioCodec,resolution,fps,pixelFormat,sampleRate},output:{container,videoCodec,audioCodec,resolution,fps,pixelFormat,sampleRate}}. Unknowns are null/absent, not invented zero. Waiting sessions may omit measurements.
Count stdout bytes using a backpressure-preserving Transform before HTTP. Maintain bounded one-second byte buckets for an approximately five-second current Mbps rate, lifetime average, highest sampled rate, output age and total bytes. Zero the current rate after idle time and report no recent output after five seconds without bytes. Do not add provider connections for telemetry. Parse FFmpeg progress/metadata from stderr using the flags below, keeping partial lines bounded to 4096 characters. Retain only whitelisted numeric fields and container, codec, resolution, fps, pixel format and sample rate; distinguish Input and Output sections. Discard raw diagnostics immediately. Parse frame, fps, out_time_us (divide by 1,000,000), speed, bitrate, drop_frames, dup_frames and progress timestamp; N/A stays unknown. Metadata source/output FPS is distinct from processing FPS, which is not browser-rendered FPS. Output throughput is not provider download speed, received/acknowledged bytes or watched bytes. Always redact source paths/queries. Remove per-stream stats on cleanup; retain only cumulative byte/start counters, not browsing history. Test metadata/progress parsing, nulls, accurate bytes/rates and decay to zero, API security, no credential/token leakage, dynamic refresh and pause behavior.

EXISTING WEBSITE STATUS INDICATORS
Both indicators are on the right. Hover/focus accelerates the shared poll to about two seconds while either panel is open and shows the telemetry above. Otherwise the visible-page cadence is 15 seconds. Background updates do not flicker readiness to Checking. Older schema-2 helpers remain supported but show an update hint for telemetry. The local dashboard polls /status independently at the selected interval.
The main window and playback window share one health subscription. The browser polls /health every 15 seconds while visible, checks again when visible, coalesces concurrent calls and allows Retry; fetch has an eight-second timeout and sends no credentials. It shows green only for ready:true with healthSchema:2, red for unreachable/needs attention, amber for an older helper, and neutral while checking. Hover/focus shows IP 127.0.0.1, port 19876, last check, latency, helper/FFmpeg versions, encoders, system summary and sessions. Clicking opens the fixed http://127.0.0.1:19876/ in another tab with noopener/noreferrer. A failed browser fetch cannot distinguish not-running from CORS, network or permission blocking; do not claim the helper is uninstalled. If the page loads but the indicator is red, explain local-network permission and origin settings. If the helper is stopped its own status page cannot load. The helper must implement the contract above; another copy of the website is not needed.

POST /sessions: require application/json; cap incoming request bytes at 8192. Body is {"url":"<complete HTTP or HTTPS provider stream URL>","mode":"remux"} or mode "compatible". Parse with URL. Reject protocols other than http:/https:, URL username/password userinfo, malformed URLs, hosts absent from the trusted allowlist, and unknown modes. Credentials embedded in the URL path/query are permitted because this is how the provider protocol authenticates. At most two sessions at once. Generate an unpredictable ID from 24 cryptographically random bytes, encoded as 48 lowercase hexadecimal characters. Keep {source URL, mode, creating origin, creation timestamp, process/response handles} in memory. Return 201 application/json, {"id":"<48-character-id>"}. Do not start FFmpeg until the stream GET. The browser expects this POST within ten seconds.

GET /sessions/<id>/stream: validate the ID and origin ownership. Start one FFmpeg process for that session, return 200 Content-Type: video/mp2t and stream FFmpeg stdout directly with backpressure. No Content-Length; do not buffer the whole movie or write a complete output file. Reject a second simultaneous stream GET for the same session with 409. The frontend uses mpegts.createPlayer({type:"mpegts",isLive:true,url:helperStreamUrl},{enableWorker:false}), attaches a video element and starts playback.

DELETE /sessions/<id>: terminate that session's FFmpeg, disconnect its streaming response, remove the session; return 200 JSON {"stopped":true}. Unknown/expired IDs return 404. The browser sends this with fetch keepalive when closing or switching modes. It may race with the stream disconnect, so repeated cleanup must be safe.

Use JSON {"error":"safe readable message"} for errors before streaming starts: 400 bad input/source/mode, 403 forbidden host/origin, 404 absent session, 405 unsupported method, 409 already streaming, 413 oversized body, 415 wrong content type, 429 session limit, 503 missing FFmpeg, 502 upstream/conversion failure, 500 unexpected helper failure. After response bytes start, terminate a failed stream; never append JSON to video bytes. Do not leak source URLs or FFmpeg stderr in errors.

FFMPEG PIPELINE
Spawn without a shell, passing each argument separately (never concatenate a shell command with the source URL). Common input arguments:
-hide_banner -loglevel info -nostats -stats_period 1 -progress pipe:2 -nostdin -re -rw_timeout 15000000 -protocol_whitelist http,https,tcp,tls,crypto -i <sourceUrl>
Then select the first video and optional first audio, discard subtitles/data:
-map 0:v:0 -map 0:a:0? -sn -dn
For mode remux (the website calls this Local fast):
-c:v copy
For mode compatible (Local compatibility):
-c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -threads 2
For both modes finish with:
-c:a aac -ac 2 -b:a 160k -f mpegts -mpegts_flags +resend_headers pipe:1
Ensure output pipe:1 works with the input protocol whitelist. Parse stderr only for bounded telemetry fields above, then discard it without logging because it can contain passwords. Keep stdout exclusively for video and stderr for diagnostics/progress on all platforms. Copy mode is not guaranteed for every codec; compatibility converts to H.264/AAC. Pace input using -re. Handle spawn failure, nonzero exit, EOF, errors and cancellation without leaked processes. Fail cleanly when the port is occupied. Do not claim success merely because a session was created.

LIFECYCLE AND SECURITY
Disconnecting the browser stream, deleting a session, or shutting down the helper must terminate FFmpeg and remove session state. Cleanup must be idempotent, with a bounded graceful shutdown and forced termination fallback. Remove unused sessions after 30 seconds (a periodic sweep is acceptable). Never install a startup service silently. Bind to loopback and validate Host to resist DNS rebinding. Origins and unpredictable session IDs prevent arbitrary websites from using an active session; they do not protect against malicious local applications. Local privileged processes may inspect FFmpeg's command line. FFmpeg can follow upstream redirects and nested playlists: an initial-host check does not enforce every downstream destination. Only allow user-trusted providers, restrict FFmpeg protocols as above and document this boundary; do not present this as a general arbitrary-URL proxy. Never add credentials to examples, analytics, screenshots, fixtures or logs.

${platform === "Windows" ? `WINDOWS DELIVERY
Provide PowerShell instructions. Detect Node.js and FFmpeg with Get-Command and verify ffmpeg -version and ffprobe -version. Explain installation through official Node.js downloads and a trusted FFmpeg distribution/package manager; verify current package identifiers rather than guessing. Support paths with spaces. Use child_process.spawn with windowsHide:true and shell:false so FFmpeg does not open extra windows. Supply an easy start script that works regardless of the shell's current directory, shows meaningful setup errors, and explains how to stop it. Verify Windows process cleanup rather than assuming POSIX signals behave identically.` : platform === "macOS" ? `MACOS DELIVERY
Provide Terminal instructions for Apple Silicon and Intel Macs. Detect architecture and existing Node.js/FFmpeg; use official Node.js or a verified Homebrew installation route. Account for /opt/homebrew/bin versus /usr/local/bin and allow an explicit FFmpeg path. Keep libx264 software conversion as the compatibility baseline; hardware encoding is optional and must not alter the protocol. Supply a start script with correct script-relative paths and instructions for chmod +x, starting and stopping it. Explain that the browser/OS may prompt for local-network access. Any LaunchAgent/login startup is optional and must include uninstall instructions.` : `LINUX DELIVERY
Provide shell instructions for Debian/Ubuntu and Fedora, noting that package availability differs by distribution. Detect existing Node.js and FFmpeg; verify current official installation guidance and that FFmpeg includes libx264 and AAC encoders. Do not assume every distro FFmpeg package has the same encoders. Supply a script with correct script-relative paths, executable-permission instructions, and start/stop commands. Run as a normal user, not root. Any systemd user service is optional and must include uninstall instructions. Do not open a firewall port or bind on all interfaces.`}

DELIVERABLES AND ACCEPTANCE TESTS
Return complete files (server.mjs, package.json with a start script, .env.example, .gitignore, README, OS start script and meaningful tests), plus a reproducible dependency lockfile or instructions to generate one. Do not return pseudocode or require this original project. Explain how to paste the files into a folder, install dependencies, confirm FFmpeg, configure the origin/provider, start the helper, open the existing website on this same computer, choose Local fast or Local compatibility, and allow browser local-network access when prompted.
Test health schema 2, accurate readiness, FFmpeg missing/timeout and missing encoders, health-check caching; root HTML with no Origin, disallowed Origin, HTML escaping and security headers; health with the correct Origin; forbidden/missing API Origin and wrong Host; preflight; malformed/oversized JSON; disallowed source/protocol; both modes; session limits; duplicate stream GET; origin ownership; expiry; deletion/disconnect/shutdown process cleanup; missing FFmpeg and upstream failure. Use a generated short test video and temporary local fixture provider explicitly allowed only in tests. Verify output codecs with ffprobe and actual advancing video frames in desktop Chrome/Edge. Do not disable web security for tests. Report exactly what passed and what could not be verified. Never use real IPTV secrets in fixtures.
Explain limitations: no seeking/resume, subtitles or alternate audio selection in this version; VOD starts at the beginning; compatibility can consume substantial CPU for 4K; provider access/account restrictions remain; the helper runs on the viewing computer; website/catalogue traffic still uses Vercel but local-mode video does not. Troubleshoot port conflicts, PATH/FFmpeg problems, origin mismatch, provider allowlist mismatch, local-network permission, no picture in fast mode, and provider outages separately.
`;
}
